name: Test Code Samples

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
        working-directory: ./code-samples/reverse-otp-node
      - name: Run tests
        run: npm test
        working-directory: ./code-samples/reverse-otp-node

  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: ./code-samples/reverse-otp-python
      - name: Run tests
        run: python -m unittest discover
        working-directory: ./code-samples/reverse-otp-python
